# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  
  config.vm.network "private_network", ip: "192.168.42.4"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end

  config.vm.provision "shell", path: "setup.sh"

  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=777,fmode=777"]
end
